### PR TITLE
Feature/first fixes after publication

### PR DESCRIPTION
**Pull request by pagarcia**
For this PR, I've learned how to automatically deploy tagged main updates as PyPI releases. 
I've also tested the deployment of documentation to the splineops.github.io website.
Any other relatively simple fixes after first publication come here.

### CODE REVIEW

**Comment by dperdios** [comment]
Could not test everything, especially the automatic publish to PyPi. The other things are ok to merge. Few questions / remarks about the automatic publishing to PyPi.

How did you test this feature? Is it through the testrepo (https://github.com/splineops/testrepo)?

Is this automatic publishing ideal? I like the concept but it also means that whenever someone pushes a `v` tag to `main` it will trigger an automatic publish to PyPi, correct?

Is there a way to review this behavior? We probably need a step-by-step guide in the `README` to publish a new version to PyPi. Could you draft something in the PR?

**Comment by pagarcia** [comment]
Actually the only "automation" here is the step from tagging the main branch with a new version, into having it published on PyPI. This step is just running the line:

`hatch publish --user __token__ --password $PYPI_TOKEN`

on `.github/publish-to-pypi.yml`

Otherwise, it's about running this line manually every time a PyPI release is needed. As a new release is needed every time there's a push to main + new tagging, I find it quite convenient.
It is a similar automation to that of the documentation building, using Github Actions.

Yes, I have tested it in testrepo. Though, as with Github Actions on the server, it can't be 100% tested locally or in different repos, as there are very specific variables such as in this case the $PYPI_TOKEN which is specific to this repository (you can find it in the Settings of the repo). Though, I'm confident it will work!

**Comment by dperdios** [comment]
Thanks for the additional information.

My main question remains: what does prevent an erroneous tagging in the `main` branch that will trigger a new release directly submitted to PyPi?

Technically it should be "safe" as we require pull requests, reviews and tests before merging to `main`. Not sure there exist a way to be safe even when publishing manually. Is the strategy you selected used by other "known" projects?

For me whatever the strategy selected, we need some `README` info to publish to PyPi. Are you ok to draft something?

Thanks!

**Comment by pagarcia** [comment]
You got me here with this question:

> My main question remains: what does prevent an erroneous tagging in the main branch that will trigger a new release directly submitted to PyPi?

Honestly, I have no idea of what an erroneous tagging could be! Could you show me an example?

As for other known solutions, I have never seen an automated mechanism so far. It seems everyone might be doing the PyPI release by hand.

What I propose: let's put aside the automated PyPI publishing for the moment, ie remove the file 
.github/workflows/publish-to-pypi.yml and accept the rest of this PR, which is more important (as it involves the documentation deployment and .binder virtual machine). We'll address the PyPI automation at later stage.

Do you agree, and do you want me to do this file removing?

**Comment by dperdios** [comment]
For me the risk is that I can personally tag any commit on `main`, say with `v1.0.0` and this would trigger a publication on PyPi. This is somehow unsafe in my opinion.

I just googled what is the standard pipeline and maybe this what should be deployed:
https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

So if you want to get that PR quickly through, it's ok to remove the automatic publishing to PyPi. I will open an issue about that so you can build on that.

Sound good?

**Comment by pagarcia** [comment]
Perfect, I just removed the publish-to-pypi.yml.
Please check it out and accept the PR.

**Comment by dperdios** [comment]
All good for me - PR accepted. You can proceed with merging and publishing

**Pull request merged**
